### PR TITLE
Use halfwidth alphabets for inputs in data

### PR DESCRIPTION
**Pull request by llskyhi**
現在データ内入力の全角アルファベットを半角にしました。

例：
- `ｔｍｔ` → `tmt`
- `ほろｊｐ` → `ほろjp`

[CONTRIBUTING.md#アルファベットで検索する用語](https://github.com/heppokofrontend/hololive-dictionary/blame/2e49dffb3457db3c3e45ffc8deab12c1de34d735/CONTRIBUTING.md#L43-L51)（ ec233acd・#13 から）：
> Windows ではアルファベットの大文字小文字を区別しないため、データ内では全角小文字統一で登録します。

変更のひとつの `ほろｊｐ` は純粋に「アルファベットで検索する」ではないが、順番的に新しい ca765a39・#16 は `ほろen` と半角で `en` を使ったため、この PR を作成しました。

私は日本語下手です、認識が間違っていたらすみません。

### CODE REVIEW

**Comment by heppokofrontend** [comment]
Hi @llskyhi, I appreciate your pull request!

~~When typing in Japanese, if you switch to uppercase English letters while typing in hiragana, you need to press the Shift key afterward to type in lowercase.~~
When typing in Japanese, if we switch to uppercase English letters while typing in hiragana (press the Shift key), English letters will be half-width lowercase.
“ほろen” is a special case...

So, before building, it’s correct to use full-width characters.

I really appreciate the thought. Thank you for all your contributions!

p.s.
You are welcome to submit PRs in English from now on (though Japanese is, of course, very welcome too!).
I rewrote the Japanese text to make it easier for machine translation. I hope it made a difference, though...
https://github.com/heppokofrontend/hololive-dictionary/compare/66a4ae85ab9a7dca3de1ea1c38de16264e245df8...b41ccd867089eeef4625f6b4dca521476f63ab43#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055

**Comment by llskyhi** [comment]
Thanks for the kind reply!

I feel sorry because seems that when I read this ..
> データ内では全角小文字統一で登録します

.. my brain somehow misunderstood that it's "use halfwidth, lower case in liver data", but it's actually "use fullwidth, lower case in liver data".

So yes, `ｔｍｔ` in fullwidth is how it meet the intention😊

But now I'm curious about why ca765a39(#16) changed these:
- [`mori-calliope.ts`](https://github.com/heppokofrontend/hololive-dictionary/commit/ec233acdca13f75ab06f07f8c223fc46564be659?diff=split&w=0#diff-28180e4070506751bac4d210872438dcab17ee0dfee9424522b7711f2a63c314R20-R23): `ｍｙｔｈ` → `myth`
- [`momosuzu-nene.ts`](https://github.com/heppokofrontend/hololive-dictionary/commit/ec233acdca13f75ab06f07f8c223fc46564be659?diff=unified&w=0#diff-4b71474473825e5d1a3a5776b3d5262017131976bffe0c88e0b337f26ab46b0fR20): `ｖ` → `v`

I can not find the key making `ｔｍｔ` and `ｍｙｔｈ` different ...

**Comment by llskyhi** [comment]
Besides, I also wonder how do `ほろen`  and `ほろid` benefit?  
I don't know how others use IME, but for reference I, using Microsoft IME, usually type hiragana with yomi, and I think that's how this dictionary mainly helps.
(Not sure if I am using word "yomi" right - I mean the way typing `ho` to get `ほ`.)
When I type `horoen`, isn't the [`ほろえｎ`](https://github.com/heppokofrontend/hololive-dictionary/blob/750485ec07ea6f0f4b910f4a92a56b148a390554/src/dictionary/hololive/index.ts#L49) enough?

> When typing in Japanese, if you switch to uppercase English letters while typing in hiragana, you need to press the Shift key afterward to type in lowercase.
> “ほろen” is a special case...

I tried to get `ほろen` by this key stroke sequence (with caps lock off) ..
`h`, `o`, `r`, `o`, shift+`e`, backspace, `e`, `n`
.. and successfully to convert to `HololiveEn`.
But when do people type this if they can simply type `ほろえｎ`?
Is this for MAC or Google IME or ..?

**Comment by heppokofrontend** [comment]
@llskyhi Oh! Sorry for the late reply. I've been a bit too busy with daily life.

> I tried to get ほろen by this key stroke sequence (with caps lock off) ..
> h, o, r, o, shift+e, backspace, e, n
> .. and successfully to convert to HololiveEn.
> But when do people type this if they can simply type ほろえｎ?
> Is this for MAC or Google IME or ..?

That is indeed a very specific input example.

While "ほろえｎ" is sufficient, I thought it would be better to include it since it's possible to input in that way, which is why I added it. However, I now think it's redundant.
Thank you so much for your Pull Request and for sharing your thoughts!

**Pull request closed without merging**
